{
  parserClass="com.hyper.plugin.parser.HyperParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Hyper"
  psiImplClassSuffix="Impl"
  psiPackage="com.hyper.plugin.psi"
  psiImplPackage="com.hyper.plugin.psi.impl"

  elementTypeHolderClass="com.hyper.plugin.psi.HyperTypes"
  elementTypeClass="com.hyper.plugin.psi.HyperElementType"
  tokenTypeClass="com.hyper.plugin.psi.HyperTokenType"

  tokens = [
    SEPARATOR_TOKEN = "regexp:[ \t]*---[ \t]*"
    COMMENT_TOKEN = "regexp:[ \t]*#[^\r\n]*"
    HTML_LINE_TOKEN = "regexp:[ \t]*<[^\r\n]*"
    CONTROL_LINE_TOKEN = "regexp:[ \t]*(async[ \t]+)?(if|for|while|match|def|class|elif|else|case|try|except|finally|with|fragment)[ \t(:][^\r\n]*"
    END_LINE_TOKEN = "regexp:[ \t]*end[ \t]*"
    PYTHON_LINE_TOKEN = "regexp:[^\r\n]+"
  ]
}

hyperFile ::= root_element

root_element ::= element* {
  implements="com.intellij.psi.PsiLanguageInjectionHost"
  mixin="com.hyper.plugin.psi.impl.HyperRootMixin"
}

private element ::= separator | comment_line | html_line | control_line | end_line | python_line

separator ::= SEPARATOR_TOKEN
comment_line ::= COMMENT_TOKEN
html_line ::= HTML_LINE_TOKEN {
  implements="com.intellij.psi.PsiLanguageInjectionHost"
  mixin="com.hyper.plugin.psi.impl.HyperHtmlLineMixin"
}
control_line ::= CONTROL_LINE_TOKEN
end_line ::= END_LINE_TOKEN
python_line ::= PYTHON_LINE_TOKEN
